spring:
  application:
    name: crud
  redis:
    host: 192.168.88.106
    port: 6379
    password: zxx1994
  datasource:
    password: 1234
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/date?useUnicode=true&characterEncoding=utf8
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #thymeleaf
  thymeleaf:
    cache: false
    suffix: .html
  #rabbitmq
  rabbitmq:
    template:
      retry:
        enabled: true
    password: admin
    port: 5672
    host: ${spring.cloud.client.ipAddress}
    virtual-host: /
    username: admin
#euraka
management:
  endpoints:
    web:
      exposure:
        exclude: "*"
eureka:
  instance:
    instance-id: ${spring.application.name}.${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 60
    lease-renewal-interval-in-seconds: 15
  client:
    eureka-service-url-poll-interval-seconds: 300
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${spring.cloud.client.ipAddress}:3001/eureka/
    registry-fetch-interval-seconds: 10
#actuator
info:
  number: 15282648585
  provider: ${eureka.instance.instance-id}
  groupId: ${project.groupId}
  artifactId: ${project.artifactId}
  version: ${project.version}
server:
  port: 80
#logging



