spring:
  application:
    name: spider-load-config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9898
#actuator
info:
  number: 15282648585
  provider: ${eureka.instance.instance-id}
  groupId: ${project.groupId}
  artifactId: ${project.artifactId}
  version: ${project.version}
  urlLocation: http://${eureka.instance.instance-id}:/${server.port}/load
redisDb:
  config: redisKey
  webSiteCnf: webSiteCnfList
  urlRuleCnf: urlRuleCnf
  domRuleCnf: domRuleCnf
  seedsList: seedList
  undoneList: undoneList
  doneList: doneList
  redirectList: redirectList


