#######配置信息
my:
  queue:
    maxSize: 500
  #待解析数据 redis list key
  responseList:
    redisKey: responseList
  #解析器 hashmap key
  domain:
    mapName: rule
  #任务执行线程数量
  fetchercore:
    maxThread: 20
#############以上为自定义配置
spring:
  application:
    name: MyPares
  redis:
    host: 192.168.88.106
    #host: 192.168.0.101
    port: 6379
    password: zxx1994
  datasource:
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/date?useUnicode=true&characterEncoding=utf8
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  output:
    ansi:
      enabled: always
#euraka
management:
  security:
    enabled: false
eureka:
  instance:
    instance-id: ${spring.application.name}.${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 60
    lease-renewal-interval-in-seconds: 15
  client:
    eureka-service-url-poll-interval-seconds: 300
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${spring.cloud.client.ipAddress}:3001/eureka/
    registry-fetch-interval-seconds: 10
#actuator
info:
  number: 15282648585
  provider: ${eureka.instance.instance-id}
  groupId: ${project.groupId}
  artifactId: ${project.artifactId}
  version: ${project.version}
server:
  port: 9940
