
spring:
  #ActiveMQ 配置
  activemq:
    broker-url: tcp://192.168.88.106:61616
#datasource 配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/date?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
 #Redis 配置
  redis:
    host: 192.168.88.106
    port: 6379
    password: zxx1994
    timeout: 4000
    pool:
      max-wait: 5000